In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import roc_auc_score, confusion_matrix, precision_recall_fscore_support, classification_report
from scipy import signal
from sklearn.preprocessing import StandardScaler
from tqdm import tqdm
import os

In [2]:
dataframes = []
directory_path = os.path.join(os.getcwd(), 'tdcsfog_data')
print(directory_path)

/Users/Mateo/FOGproject/notebooks/tdcsfog_data


In [16]:
for filename in os.listdir(directory_path):
    if filename.endswith('.csv'):
        # Full path to the file
        file_path = os.path.join(directory_path, filename)
        # Extract patient ID from the file name (before '.csv')
        patient_id = filename.split('.')[0]
        # Read the CSV file
        df = pd.read_csv(file_path)
        # Add patient ID column
        df['PatientID'] = patient_id
        # Append to the list of dataframes
        dataframes.append(df)

# Combine all dataframes into one
tdcsfog_df = pd.concat(dataframes, ignore_index=True)

tdcsfog_df.head(10)

Time      AccV     AccML     AccAP  StartHesitation  Turn  Walking  \
0     0 -9.802023 -0.436305 -1.606585                0     0        0   
1     1 -9.802450 -0.443045 -1.599153                0     0        0   
2     2 -9.803275 -0.439261 -1.602125                0     0        0   
3     3 -9.801431 -0.436956 -1.597653                0     0        0   
4     4 -9.800925 -0.434741 -1.600627                0     0        0   
5     5 -9.800947 -0.433229 -1.599137                0     0        0   
6     6 -9.797858 -0.436299 -1.599136                0     0        0   
7     7 -9.799281 -0.437771 -1.597652                0     0        0   
8     8 -9.803057 -0.434677 -1.596909                0     0        0   
9     9 -9.797640 -0.431715 -1.593920                0     0        0   

    PatientID  
0  58b1cb50ad  
1  58b1cb50ad  
2  58b1cb50ad  
3  58b1cb50ad  
4  58b1cb50ad  
5  58b1cb50ad  
6  58b1cb50ad  
7  58b1cb50ad  
8  58b1cb50ad  
9  58b1cb50ad

In [17]:
class FOGPreprocessor:
    def __init__(self, sampling_rate=128, window_size=3, stride=2):
        self.sampling_rate = sampling_rate
        self.window_size = window_size
        self.stride = stride
        self.scaler = StandardScaler()
        
    def butter_bandpass_filter(self, data, lowcut=0.25, highcut=10, order=4):
        nyquist = 0.5 * self.sampling_rate
        low = lowcut / nyquist
        high = highcut / nyquist
        b, a = signal.butter(order, [low, high], btype='band')
        return signal.filtfilt(b, a, data)
    
    def create_windows(self, df, label_column):
        """
        Create overlapping windows for a specific label
        
        Args:
            df: DataFrame with sensor data
            label_column: The specific FOG type to process ('StartHesitation', 'Turn', or 'Walking')
        """
        window_samples = self.window_size * self.sampling_rate
        stride_samples = self.stride * self.sampling_rate
        
        # Apply bandpass filter to acceleration columns
        acc_columns = ['AccV', 'AccML', 'AccAP']
        filtered_data = {}
        for col in acc_columns:
            filtered_data[col] = self.butter_bandpass_filter(df[col].values)
        
        # Create DataFrame with filtered data
        filtered_df = pd.DataFrame(filtered_data)
        
        # Standardize the features
        filtered_df = pd.DataFrame(
            self.scaler.fit_transform(filtered_df),
            columns=filtered_df.columns
        )
        
        # Create sliding windows
        n_samples = len(df)
        n_windows = ((n_samples - window_samples) // stride_samples) + 1
        n_features = len(filtered_df.columns)
        
        X = np.zeros((n_windows, window_samples, n_features))
        y = np.zeros(n_windows)
        
        for i in range(n_windows):
            start_idx = i * stride_samples
            end_idx = start_idx + window_samples
            
            X[i] = filtered_df.iloc[start_idx:end_idx].values
            # Get labels for the specific FOG type
            window_labels = df.iloc[start_idx:end_idx][label_column]
            y[i] = 1 if window_labels.sum() > 0 else 0
        
        return X, y

In [18]:
class FOGDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.FloatTensor(X)
        self.y = torch.FloatTensor(y)
        
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [24]:
class BiGRUModel(nn.Module):
    def __init__(self, input_size, hidden_size=64, num_layers=2, dropout=0.3):
        super(BiGRUModel, self).__init__()
        
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        
        self.batch_norm = nn.BatchNorm1d(input_size)
        
        self.gru = nn.GRU(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            bidirectional=True,
            dropout=dropout if num_layers > 1 else 0
        )
        
        self.attention = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),
            nn.Tanh(),
            nn.Linear(hidden_size, 1),
            nn.Softmax(dim=1)
        )
        
        self.fc = nn.Sequential(
            nn.Linear(hidden_size * 2, hidden_size),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size, 1),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        x = self.batch_norm(x.transpose(1, 2)).transpose(1, 2)
        gru_out, _ = self.gru(x)
        attention_weights = self.attention(gru_out)
        context = torch.sum(attention_weights * gru_out, dim=1)
        out = self.fc(context)
        return out.squeeze()

In [25]:
class FOGTrainer:
    def __init__(self, model, device, fog_type, learning_rate=0.001):
        self.model = model.to(device)
        self.device = device
        self.fog_type = fog_type
        self.criterion = nn.BCELoss()
        self.optimizer = optim.Adam(model.parameters(), lr=learning_rate)
        
    def train_epoch(self, train_loader):
        self.model.train()
        total_loss = 0
        
        for batch_X, batch_y in train_loader:
            batch_X, batch_y = batch_X.to(self.device), batch_y.to(self.device)
            
            self.optimizer.zero_grad()
            outputs = self.model(batch_X)
            loss = self.criterion(outputs, batch_y)
            
            loss.backward()
            self.optimizer.step()
            
            total_loss += loss.item()
            
        return total_loss / len(train_loader)
    
    def evaluate(self, val_loader):
        self.model.eval()
        total_loss = 0
        all_preds = []
        all_labels = []
        
        with torch.no_grad():
            for batch_X, batch_y in val_loader:
                batch_X, batch_y = batch_X.to(self.device), batch_y.to(self.device)
                outputs = self.model(batch_X)
                loss = self.criterion(outputs, batch_y)
                total_loss += loss.item()
                
                all_preds.extend(outputs.cpu().numpy())
                all_labels.extend(batch_y.cpu().numpy())
        
        all_preds = np.array(all_preds)
        all_labels = np.array(all_labels)
        pred_labels = (all_preds > 0.5).astype(int)
        
        # Calculate metrics with zero division handling
        precision, recall, f1, _ = precision_recall_fscore_support(all_labels, pred_labels, 
                                                                average='binary',
                                                                zero_division=0)
        
        # Handle case where all predictions are the same class
        try:
            auc = roc_auc_score(all_labels, all_preds)
        except:
            auc = 0.0
            
        conf_matrix = confusion_matrix(all_labels, pred_labels)
        
        # Get detailed classification report with zero division handling
        report = classification_report(all_labels, pred_labels, 
                                    output_dict=True,
                                    zero_division=0)
        
        return {
            'loss': total_loss / len(val_loader),
            'auc': auc,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            'confusion_matrix': conf_matrix,
            'classification_report': report
        }
    
    def train(self, train_loader, val_loader, num_epochs=50, patience=5):
        best_val_f1 = 0
        patience_counter = 0
        best_metrics = None
        
        for epoch in range(num_epochs):
            train_loss = self.train_epoch(train_loader)
            val_metrics = self.evaluate(val_loader)
            
            print(f'\nEpoch {epoch+1}/{num_epochs} - {self.fog_type}:')
            print(f'Train Loss: {train_loss:.4f}')
            print(f'Val Loss: {val_metrics["loss"]:.4f}')
            report = val_metrics['classification_report']
            
            print(f'Val AUC: {val_metrics["auc"]:.4f}')
            print('\nDetailed Metrics:')
            print(f"Weighted Precision: {report['weighted avg']['precision']:.4f}")
            print(f"Weighted Recall: {report['weighted avg']['recall']:.4f}")
            print(f"Weighted F1-score: {report['weighted avg']['f1-score']:.4f}")
            print(f"Support: {report['weighted avg']['support']}")
            
            print('\nClass-wise Metrics:')
            class_metrics = val_metrics['classification_report']
            try:
                print(f"Class 0 (No FOG) - Precision: {class_metrics['0']['precision']:.4f}, "
                      f"Recall: {class_metrics['0']['recall']:.4f}, F1: {class_metrics['0']['f1-score']:.4f}, "
                      f"Support: {class_metrics['0']['support']}")
            except KeyError:
                print("No predictions for Class 0 (No FOG)")
                
            try:
                print(f"Class 1 (FOG) - Precision: {class_metrics['1']['precision']:.4f}, "
                      f"Recall: {class_metrics['1']['recall']:.4f}, F1: {class_metrics['1']['f1-score']:.4f}, "
                      f"Support: {class_metrics['1']['support']}")
            except KeyError:
                print("No predictions for Class 1 (FOG)")
                
            conf_matrix = val_metrics['confusion_matrix']
            # Calculate class distribution from confusion matrix
            print("\nClass Distribution:")
            true_dist = conf_matrix.sum(axis=1)
            pred_dist = conf_matrix.sum(axis=0)
            print(f"Labels distribution: {dict(enumerate(true_dist))}")
            print(f"Predictions distribution: {dict(enumerate(pred_dist))}")
            print('Confusion Matrix:')
            print(val_metrics['confusion_matrix'])
            
            if val_metrics['f1'] > best_val_f1:
                best_val_f1 = val_metrics['f1']
                best_metrics = val_metrics
                patience_counter = 0
                torch.save(self.model.state_dict(), f'best_model_{self.fog_type}.pth')
            else:
                patience_counter += 1
                if patience_counter >= patience:
                    print(f'\nEarly stopping triggered for {self.fog_type}')
                    print(f'Best metrics achieved:')
                    print(f"F1 Score: {best_metrics['f1']:.4f}")
                    print(f"Precision: {best_metrics['precision']:.4f}")
                    print(f"Recall: {best_metrics['recall']:.4f}")
                    print(f"AUC: {best_metrics['auc']:.4f}")
                    break
            
            print('-' * 50)

def train_fog_models(df):
    """Train separate models for each FOG type"""
    preprocessor = FOGPreprocessor()
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    fog_types = ['StartHesitation', 'Turn', 'Walking']
    
    results = {}
    for fog_type in fog_types:
        print(f"\nTraining model for {fog_type}")
        
        # Preprocess data for this FOG type
        X, y = preprocessor.create_windows(df, fog_type)
        
        # Create datasets
        dataset = FOGDataset(X, y)
        train_size = int(0.8 * len(dataset))
        val_size = len(dataset) - train_size
        train_dataset, val_dataset = torch.utils.data.random_split(dataset, [train_size, val_size])
        
        # Create data loaders
        train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
        val_loader = DataLoader(val_dataset, batch_size=32)
        
        # Initialize model and trainer
        model = BiGRUModel(input_size=X.shape[2])
        trainer = FOGTrainer(model, device, fog_type)
        
        # Train model
        trainer.train(train_loader, val_loader)
        
        # Store results
        results[fog_type] = {
            'model': model,
            'metrics': trainer.evaluate(val_loader)
        }
    
    return results

In [26]:
# Assuming you have your data in tdcsfog_df
results = train_fog_models(tdcsfog_df)

# Print final results for each FOG type
for fog_type, result in results.items():
    print(f"\nFinal results for {fog_type}:")
    metrics = result['metrics']
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1 Score: {metrics['f1']:.4f}")
    print(f"AUC: {metrics['auc']:.4f}")
    print("Confusion Matrix:")
    print(metrics['confusion_matrix'])


Training model for StartHesitation



Epoch 1/50 - StartHesitation:
Train Loss: 0.1812
Val Loss: 0.1431
Val AUC: 0.8611

Detailed Metrics:
Weighted Precision: 0.9097
Weighted Recall: 0.9538
Weighted F1-score: 0.9312
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5518, 1: 0}
Confusion Matrix:
[[5263    0]
 [ 255    0]]
--------------------------------------------------



Epoch 2/50 - StartHesitation:
Train Loss: 0.1503
Val Loss: 0.1333
Val AUC: 0.8805

Detailed Metrics:
Weighted Precision: 0.9385
Weighted Recall: 0.9543
Weighted F1-score: 0.9349
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5501, 1: 17}
Confusion Matrix:
[[5256    7]
 [ 245   10]]
--------------------------------------------------



Epoch 3/50 - StartHesitation:
Train Loss: 0.1431
Val Loss: 0.1275
Val AUC: 0.8842

Detailed Metrics:
Weighted Precision: 0.9471
Weighted Recall: 0.9570
Weighted F1-score: 0.9426
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5472, 1: 46}
Confusion Matrix:
[[5249   14]
 [ 223   32]]
--------------------------------------------------



Epoch 4/50 - StartHesitation:
Train Loss: 0.1351
Val Loss: 0.1274
Val AUC: 0.8936

Detailed Metrics:
Weighted Precision: 0.9499
Weighted Recall: 0.9585
Weighted F1-score: 0.9460
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5458, 1: 60}
Confusion Matrix:
[[5246   17]
 [ 212   43]]
--------------------------------------------------



Epoch 5/50 - StartHesitation:
Train Loss: 0.1305
Val Loss: 0.1202
Val AUC: 0.9013

Detailed Metrics:
Weighted Precision: 0.9521
Weighted Recall: 0.9601
Weighted F1-score: 0.9526
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5407, 1: 111}
Confusion Matrix:
[[5225   38]
 [ 182   73]]
--------------------------------------------------



Epoch 6/50 - StartHesitation:
Train Loss: 0.1266
Val Loss: 0.1154
Val AUC: 0.9090

Detailed Metrics:
Weighted Precision: 0.9560
Weighted Recall: 0.9625
Weighted F1-score: 0.9564
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5392, 1: 126}
Confusion Matrix:
[[5224   39]
 [ 168   87]]
--------------------------------------------------



Epoch 7/50 - StartHesitation:
Train Loss: 0.1212
Val Loss: 0.1129
Val AUC: 0.9154

Detailed Metrics:
Weighted Precision: 0.9577
Weighted Recall: 0.9636
Weighted F1-score: 0.9582
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5382, 1: 136}
Confusion Matrix:
[[5222   41]
 [ 160   95]]
--------------------------------------------------



Epoch 8/50 - StartHesitation:
Train Loss: 0.1167
Val Loss: 0.1173
Val AUC: 0.9219

Detailed Metrics:
Weighted Precision: 0.9506
Weighted Recall: 0.9580
Weighted F1-score: 0.9434
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5475, 1: 43}
Confusion Matrix:
[[5253   10]
 [ 222   33]]
--------------------------------------------------



Epoch 9/50 - StartHesitation:
Train Loss: 0.1144
Val Loss: 0.1121
Val AUC: 0.9235

Detailed Metrics:
Weighted Precision: 0.9576
Weighted Recall: 0.9630
Weighted F1-score: 0.9589
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5359, 1: 159}
Confusion Matrix:
[[5209   54]
 [ 150  105]]
--------------------------------------------------



Epoch 10/50 - StartHesitation:
Train Loss: 0.1082
Val Loss: 0.1153
Val AUC: 0.9172

Detailed Metrics:
Weighted Precision: 0.9591
Weighted Recall: 0.9599
Weighted F1-score: 0.9595
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5274, 1: 244}
Confusion Matrix:
[[5158  105]
 [ 116  139]]
--------------------------------------------------



Epoch 11/50 - StartHesitation:
Train Loss: 0.1029
Val Loss: 0.1061
Val AUC: 0.9300

Detailed Metrics:
Weighted Precision: 0.9600
Weighted Recall: 0.9641
Weighted F1-score: 0.9613
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5335, 1: 183}
Confusion Matrix:
[[5200   63]
 [ 135  120]]
--------------------------------------------------



Epoch 12/50 - StartHesitation:
Train Loss: 0.0992
Val Loss: 0.1042
Val AUC: 0.9322

Detailed Metrics:
Weighted Precision: 0.9602
Weighted Recall: 0.9650
Weighted F1-score: 0.9612
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5358, 1: 160}
Confusion Matrix:
[[5214   49]
 [ 144  111]]
--------------------------------------------------



Epoch 13/50 - StartHesitation:
Train Loss: 0.0926
Val Loss: 0.1087
Val AUC: 0.9275

Detailed Metrics:
Weighted Precision: 0.9596
Weighted Recall: 0.9648
Weighted F1-score: 0.9601
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5375, 1: 143}
Confusion Matrix:
[[5222   41]
 [ 153  102]]
--------------------------------------------------



Epoch 14/50 - StartHesitation:
Train Loss: 0.0887
Val Loss: 0.1027
Val AUC: 0.9355

Detailed Metrics:
Weighted Precision: 0.9608
Weighted Recall: 0.9652
Weighted F1-score: 0.9619
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5347, 1: 171}
Confusion Matrix:
[[5209   54]
 [ 138  117]]
--------------------------------------------------



Epoch 15/50 - StartHesitation:
Train Loss: 0.0829
Val Loss: 0.1164
Val AUC: 0.9313

Detailed Metrics:
Weighted Precision: 0.9639
Weighted Recall: 0.9679
Weighted F1-score: 0.9632
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5263, 1: 255}
Predictions distribution: {0: 5382, 1: 136}
Confusion Matrix:
[[5234   29]
 [ 148  107]]

Early stopping triggered for StartHesitation
Best metrics achieved:
F1 Score: 0.5571
Precision: 0.5697
Recall: 0.5451
AUC: 0.9172



Training model for Turn



Epoch 1/50 - Turn:
Train Loss: 0.4431
Val Loss: 0.3792
Val AUC: 0.8808

Detailed Metrics:
Weighted Precision: 0.8217
Weighted Recall: 0.8273
Weighted F1-score: 0.8227
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4205, 1: 1313}
Confusion Matrix:
[[3612  360]
 [ 593  953]]
--------------------------------------------------



Epoch 2/50 - Turn:
Train Loss: 0.3729
Val Loss: 0.3456
Val AUC: 0.9049

Detailed Metrics:
Weighted Precision: 0.8419
Weighted Recall: 0.8452
Weighted F1-score: 0.8429
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4110, 1: 1408}
Confusion Matrix:
[[3614  358]
 [ 496 1050]]
--------------------------------------------------



Epoch 3/50 - Turn:
Train Loss: 0.3531
Val Loss: 0.3334
Val AUC: 0.9116

Detailed Metrics:
Weighted Precision: 0.8493
Weighted Recall: 0.8532
Weighted F1-score: 0.8475
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4294, 1: 1224}
Confusion Matrix:
[[3728  244]
 [ 566  980]]
--------------------------------------------------



Epoch 4/50 - Turn:
Train Loss: 0.3416
Val Loss: 0.3293
Val AUC: 0.9138

Detailed Metrics:
Weighted Precision: 0.8512
Weighted Recall: 0.8541
Weighted F1-score: 0.8521
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4101, 1: 1417}
Confusion Matrix:
[[3634  338]
 [ 467 1079]]
--------------------------------------------------



Epoch 5/50 - Turn:
Train Loss: 0.3335
Val Loss: 0.3379
Val AUC: 0.9169

Detailed Metrics:
Weighted Precision: 0.8446
Weighted Recall: 0.8476
Weighted F1-score: 0.8390
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4409, 1: 1109}
Confusion Matrix:
[[3770  202]
 [ 639  907]]
--------------------------------------------------



Epoch 6/50 - Turn:
Train Loss: 0.3256
Val Loss: 0.3255
Val AUC: 0.9182

Detailed Metrics:
Weighted Precision: 0.8537
Weighted Recall: 0.8561
Weighted F1-score: 0.8487
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4378, 1: 1140}
Confusion Matrix:
[[3778  194]
 [ 600  946]]
--------------------------------------------------



Epoch 7/50 - Turn:
Train Loss: 0.3172
Val Loss: 0.3173
Val AUC: 0.9220

Detailed Metrics:
Weighted Precision: 0.8596
Weighted Recall: 0.8626
Weighted F1-score: 0.8602
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4132, 1: 1386}
Confusion Matrix:
[[3673  299]
 [ 459 1087]]
--------------------------------------------------



Epoch 8/50 - Turn:
Train Loss: 0.3090
Val Loss: 0.3213
Val AUC: 0.9228

Detailed Metrics:
Weighted Precision: 0.8595
Weighted Recall: 0.8550
Weighted F1-score: 0.8567
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3842, 1: 1676}
Confusion Matrix:
[[3507  465]
 [ 335 1211]]
--------------------------------------------------



Epoch 9/50 - Turn:
Train Loss: 0.3028
Val Loss: 0.3066
Val AUC: 0.9266

Detailed Metrics:
Weighted Precision: 0.8650
Weighted Recall: 0.8681
Weighted F1-score: 0.8650
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4182, 1: 1336}
Confusion Matrix:
[[3713  259]
 [ 469 1077]]
--------------------------------------------------



Epoch 10/50 - Turn:
Train Loss: 0.2938
Val Loss: 0.3028
Val AUC: 0.9288

Detailed Metrics:
Weighted Precision: 0.8609
Weighted Recall: 0.8641
Weighted F1-score: 0.8613
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4156, 1: 1362}
Confusion Matrix:
[[3689  283]
 [ 467 1079]]
--------------------------------------------------



Epoch 11/50 - Turn:
Train Loss: 0.2881
Val Loss: 0.3050
Val AUC: 0.9295

Detailed Metrics:
Weighted Precision: 0.8686
Weighted Recall: 0.8681
Weighted F1-score: 0.8683
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3954, 1: 1564}
Confusion Matrix:
[[3599  373]
 [ 355 1191]]
--------------------------------------------------



Epoch 12/50 - Turn:
Train Loss: 0.2783
Val Loss: 0.3046
Val AUC: 0.9314

Detailed Metrics:
Weighted Precision: 0.8610
Weighted Recall: 0.8643
Weighted F1-score: 0.8599
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4245, 1: 1273}
Confusion Matrix:
[[3734  238]
 [ 511 1035]]
--------------------------------------------------



Epoch 13/50 - Turn:
Train Loss: 0.2713
Val Loss: 0.2962
Val AUC: 0.9323

Detailed Metrics:
Weighted Precision: 0.8727
Weighted Recall: 0.8750
Weighted F1-score: 0.8733
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4098, 1: 1420}
Confusion Matrix:
[[3690  282]
 [ 408 1138]]
--------------------------------------------------



Epoch 14/50 - Turn:
Train Loss: 0.2632
Val Loss: 0.2940
Val AUC: 0.9367

Detailed Metrics:
Weighted Precision: 0.8739
Weighted Recall: 0.8762
Weighted F1-score: 0.8744
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4109, 1: 1409}
Confusion Matrix:
[[3699  273]
 [ 410 1136]]
--------------------------------------------------



Epoch 15/50 - Turn:
Train Loss: 0.2555
Val Loss: 0.2858
Val AUC: 0.9389

Detailed Metrics:
Weighted Precision: 0.8759
Weighted Recall: 0.8780
Weighted F1-score: 0.8764
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4099, 1: 1419}
Confusion Matrix:
[[3699  273]
 [ 400 1146]]
--------------------------------------------------



Epoch 16/50 - Turn:
Train Loss: 0.2530
Val Loss: 0.2889
Val AUC: 0.9366

Detailed Metrics:
Weighted Precision: 0.8732
Weighted Recall: 0.8757
Weighted F1-score: 0.8737
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4118, 1: 1400}
Confusion Matrix:
[[3702  270]
 [ 416 1130]]
--------------------------------------------------



Epoch 17/50 - Turn:
Train Loss: 0.2419
Val Loss: 0.2864
Val AUC: 0.9393

Detailed Metrics:
Weighted Precision: 0.8801
Weighted Recall: 0.8766
Weighted F1-score: 0.8779
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3855, 1: 1663}
Confusion Matrix:
[[3573  399]
 [ 282 1264]]
--------------------------------------------------



Epoch 18/50 - Turn:
Train Loss: 0.2359
Val Loss: 0.2826
Val AUC: 0.9389

Detailed Metrics:
Weighted Precision: 0.8796
Weighted Recall: 0.8817
Weighted F1-score: 0.8801
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4095, 1: 1423}
Confusion Matrix:
[[3707  265]
 [ 388 1158]]
--------------------------------------------------



Epoch 19/50 - Turn:
Train Loss: 0.2246
Val Loss: 0.2995
Val AUC: 0.9379

Detailed Metrics:
Weighted Precision: 0.8785
Weighted Recall: 0.8750
Weighted F1-score: 0.8763
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3856, 1: 1662}
Confusion Matrix:
[[3569  403]
 [ 287 1259]]
--------------------------------------------------



Epoch 20/50 - Turn:
Train Loss: 0.2189
Val Loss: 0.2829
Val AUC: 0.9425

Detailed Metrics:
Weighted Precision: 0.8819
Weighted Recall: 0.8808
Weighted F1-score: 0.8813
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3928, 1: 1590}
Confusion Matrix:
[[3621  351]
 [ 307 1239]]
--------------------------------------------------



Epoch 21/50 - Turn:
Train Loss: 0.2093
Val Loss: 0.3021
Val AUC: 0.9387

Detailed Metrics:
Weighted Precision: 0.8787
Weighted Recall: 0.8775
Weighted F1-score: 0.8780
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3928, 1: 1590}
Confusion Matrix:
[[3612  360]
 [ 316 1230]]
--------------------------------------------------



Epoch 22/50 - Turn:
Train Loss: 0.2032
Val Loss: 0.3205
Val AUC: 0.9385

Detailed Metrics:
Weighted Precision: 0.8817
Weighted Recall: 0.8779
Weighted F1-score: 0.8793
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3846, 1: 1672}
Confusion Matrix:
[[3572  400]
 [ 274 1272]]
--------------------------------------------------



Epoch 23/50 - Turn:
Train Loss: 0.1968
Val Loss: 0.2891
Val AUC: 0.9429

Detailed Metrics:
Weighted Precision: 0.8769
Weighted Recall: 0.8779
Weighted F1-score: 0.8773
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4016, 1: 1502}
Confusion Matrix:
[[3657  315]
 [ 359 1187]]
--------------------------------------------------



Epoch 24/50 - Turn:
Train Loss: 0.1907
Val Loss: 0.2862
Val AUC: 0.9420

Detailed Metrics:
Weighted Precision: 0.8816
Weighted Recall: 0.8826
Weighted F1-score: 0.8820
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4020, 1: 1498}
Confusion Matrix:
[[3672  300]
 [ 348 1198]]
--------------------------------------------------



Epoch 25/50 - Turn:
Train Loss: 0.1808
Val Loss: 0.3059
Val AUC: 0.9379

Detailed Metrics:
Weighted Precision: 0.8744
Weighted Recall: 0.8690
Weighted F1-score: 0.8709
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3811, 1: 1707}
Confusion Matrix:
[[3530  442]
 [ 281 1265]]
--------------------------------------------------



Epoch 26/50 - Turn:
Train Loss: 0.1760
Val Loss: 0.3330
Val AUC: 0.9384

Detailed Metrics:
Weighted Precision: 0.8788
Weighted Recall: 0.8704
Weighted F1-score: 0.8730
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3743, 1: 1775}
Confusion Matrix:
[[3500  472]
 [ 243 1303]]
--------------------------------------------------



Epoch 27/50 - Turn:
Train Loss: 0.1699
Val Loss: 0.3099
Val AUC: 0.9408

Detailed Metrics:
Weighted Precision: 0.8842
Weighted Recall: 0.8840
Weighted F1-score: 0.8841
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3964, 1: 1554}
Confusion Matrix:
[[3648  324]
 [ 316 1230]]
--------------------------------------------------



Epoch 28/50 - Turn:
Train Loss: 0.1620
Val Loss: 0.3281
Val AUC: 0.9405

Detailed Metrics:
Weighted Precision: 0.8764
Weighted Recall: 0.8789
Weighted F1-score: 0.8760
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4190, 1: 1328}
Confusion Matrix:
[[3747  225]
 [ 443 1103]]
--------------------------------------------------



Epoch 29/50 - Turn:
Train Loss: 0.1598
Val Loss: 0.3300
Val AUC: 0.9412

Detailed Metrics:
Weighted Precision: 0.8842
Weighted Recall: 0.8856
Weighted F1-score: 0.8847
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4055, 1: 1463}
Confusion Matrix:
[[3698  274]
 [ 357 1189]]
--------------------------------------------------



Epoch 30/50 - Turn:
Train Loss: 0.1503
Val Loss: 0.3275
Val AUC: 0.9386

Detailed Metrics:
Weighted Precision: 0.8801
Weighted Recall: 0.8822
Weighted F1-score: 0.8805
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 4108, 1: 1410}
Confusion Matrix:
[[3715  257]
 [ 393 1153]]
--------------------------------------------------



Epoch 31/50 - Turn:
Train Loss: 0.1468
Val Loss: 0.3132
Val AUC: 0.9414

Detailed Metrics:
Weighted Precision: 0.8828
Weighted Recall: 0.8820
Weighted F1-score: 0.8824
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3939, 1: 1579}
Confusion Matrix:
[[3630  342]
 [ 309 1237]]
--------------------------------------------------



Epoch 32/50 - Turn:
Train Loss: 0.1437
Val Loss: 0.3213
Val AUC: 0.9385

Detailed Metrics:
Weighted Precision: 0.8779
Weighted Recall: 0.8762
Weighted F1-score: 0.8769
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 3972, 1: 1546}
Predictions distribution: {0: 3911, 1: 1607}
Confusion Matrix:
[[3600  372]
 [ 311 1235]]

Early stopping triggered for Turn
Best metrics achieved:
F1 Score: 0.7935
Precision: 0.7915
Recall: 0.7956
AUC: 0.9408



Training model for Walking



Epoch 1/50 - Walking:
Train Loss: 0.1436
Val Loss: 0.1231
Val AUC: 0.8437

Detailed Metrics:
Weighted Precision: 0.9316
Weighted Recall: 0.9652
Weighted F1-score: 0.9481
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5518, 1: 0}
Confusion Matrix:
[[5326    0]
 [ 192    0]]
--------------------------------------------------



Epoch 2/50 - Walking:
Train Loss: 0.1228
Val Loss: 0.1171
Val AUC: 0.8598

Detailed Metrics:
Weighted Precision: 0.9555
Weighted Recall: 0.9656
Weighted F1-score: 0.9497
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5512, 1: 6}
Confusion Matrix:
[[5324    2]
 [ 188    4]]
--------------------------------------------------



Epoch 3/50 - Walking:
Train Loss: 0.1165
Val Loss: 0.1128
Val AUC: 0.8714

Detailed Metrics:
Weighted Precision: 0.9542
Weighted Recall: 0.9656
Weighted F1-score: 0.9500
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5510, 1: 8}
Confusion Matrix:
[[5323    3]
 [ 187    5]]
--------------------------------------------------



Epoch 4/50 - Walking:
Train Loss: 0.1111
Val Loss: 0.1100
Val AUC: 0.8743

Detailed Metrics:
Weighted Precision: 0.9564
Weighted Recall: 0.9663
Weighted F1-score: 0.9529
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5498, 1: 20}
Confusion Matrix:
[[5319    7]
 [ 179   13]]
--------------------------------------------------



Epoch 5/50 - Walking:
Train Loss: 0.1046
Val Loss: 0.1057
Val AUC: 0.8919

Detailed Metrics:
Weighted Precision: 0.9569
Weighted Recall: 0.9667
Weighted F1-score: 0.9579
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5460, 1: 58}
Confusion Matrix:
[[5301   25]
 [ 159   33]]
--------------------------------------------------



Epoch 6/50 - Walking:
Train Loss: 0.1029
Val Loss: 0.1044
Val AUC: 0.9015

Detailed Metrics:
Weighted Precision: 0.9602
Weighted Recall: 0.9679
Weighted F1-score: 0.9575
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5479, 1: 39}
Confusion Matrix:
[[5314   12]
 [ 165   27]]
--------------------------------------------------



Epoch 7/50 - Walking:
Train Loss: 0.0953
Val Loss: 0.1013
Val AUC: 0.9005

Detailed Metrics:
Weighted Precision: 0.9646
Weighted Recall: 0.9705
Weighted F1-score: 0.9637
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5449, 1: 69}
Confusion Matrix:
[[5306   20]
 [ 143   49]]
--------------------------------------------------



Epoch 8/50 - Walking:
Train Loss: 0.0930
Val Loss: 0.0994
Val AUC: 0.9069

Detailed Metrics:
Weighted Precision: 0.9630
Weighted Recall: 0.9692
Weighted F1-score: 0.9643
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5420, 1: 98}
Confusion Matrix:
[[5288   38]
 [ 132   60]]
--------------------------------------------------



Epoch 9/50 - Walking:
Train Loss: 0.0889
Val Loss: 0.1019
Val AUC: 0.9108

Detailed Metrics:
Weighted Precision: 0.9665
Weighted Recall: 0.9705
Weighted F1-score: 0.9615
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5473, 1: 45}
Confusion Matrix:
[[5318    8]
 [ 155   37]]
--------------------------------------------------



Epoch 10/50 - Walking:
Train Loss: 0.0857
Val Loss: 0.0965
Val AUC: 0.9036

Detailed Metrics:
Weighted Precision: 0.9642
Weighted Recall: 0.9703
Weighted F1-score: 0.9640
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5442, 1: 76}
Confusion Matrix:
[[5302   24]
 [ 140   52]]
--------------------------------------------------



Epoch 11/50 - Walking:
Train Loss: 0.0816
Val Loss: 0.0934
Val AUC: 0.9148

Detailed Metrics:
Weighted Precision: 0.9681
Weighted Recall: 0.9726
Weighted F1-score: 0.9676
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5431, 1: 87}
Confusion Matrix:
[[5303   23]
 [ 128   64]]
--------------------------------------------------



Epoch 12/50 - Walking:
Train Loss: 0.0769
Val Loss: 0.0987
Val AUC: 0.9144

Detailed Metrics:
Weighted Precision: 0.9617
Weighted Recall: 0.9676
Weighted F1-score: 0.9636
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5403, 1: 115}
Confusion Matrix:
[[5275   51]
 [ 128   64]]
--------------------------------------------------



Epoch 13/50 - Walking:
Train Loss: 0.0705
Val Loss: 0.0975
Val AUC: 0.9109

Detailed Metrics:
Weighted Precision: 0.9661
Weighted Recall: 0.9712
Weighted F1-score: 0.9671
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5413, 1: 105}
Confusion Matrix:
[[5290   36]
 [ 123   69]]
--------------------------------------------------



Epoch 14/50 - Walking:
Train Loss: 0.0701
Val Loss: 0.0951
Val AUC: 0.9178

Detailed Metrics:
Weighted Precision: 0.9638
Weighted Recall: 0.9686
Weighted F1-score: 0.9654
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5393, 1: 125}
Confusion Matrix:
[[5273   53]
 [ 120   72]]
--------------------------------------------------



Epoch 15/50 - Walking:
Train Loss: 0.0655
Val Loss: 0.0911
Val AUC: 0.9265

Detailed Metrics:
Weighted Precision: 0.9678
Weighted Recall: 0.9725
Weighted F1-score: 0.9681
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5420, 1: 98}
Confusion Matrix:
[[5297   29]
 [ 123   69]]
--------------------------------------------------



Epoch 16/50 - Walking:
Train Loss: 0.0605
Val Loss: 0.0959
Val AUC: 0.9298

Detailed Metrics:
Weighted Precision: 0.9665
Weighted Recall: 0.9705
Weighted F1-score: 0.9679
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5385, 1: 133}
Confusion Matrix:
[[5274   52]
 [ 111   81]]
--------------------------------------------------



Epoch 17/50 - Walking:
Train Loss: 0.0584
Val Loss: 0.0941
Val AUC: 0.9250

Detailed Metrics:
Weighted Precision: 0.9639
Weighted Recall: 0.9672
Weighted F1-score: 0.9653
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5367, 1: 151}
Confusion Matrix:
[[5256   70]
 [ 111   81]]
--------------------------------------------------



Epoch 18/50 - Walking:
Train Loss: 0.0532
Val Loss: 0.0896
Val AUC: 0.9344

Detailed Metrics:
Weighted Precision: 0.9634
Weighted Recall: 0.9679
Weighted F1-score: 0.9651
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5385, 1: 133}
Confusion Matrix:
[[5267   59]
 [ 118   74]]
--------------------------------------------------



Epoch 19/50 - Walking:
Train Loss: 0.0469
Val Loss: 0.1131
Val AUC: 0.9210

Detailed Metrics:
Weighted Precision: 0.9611
Weighted Recall: 0.9580
Weighted F1-score: 0.9594
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5296, 1: 222}
Confusion Matrix:
[[5195  131]
 [ 101   91]]
--------------------------------------------------



Epoch 20/50 - Walking:
Train Loss: 0.0474
Val Loss: 0.0919
Val AUC: 0.9376

Detailed Metrics:
Weighted Precision: 0.9686
Weighted Recall: 0.9726
Weighted F1-score: 0.9695
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5399, 1: 119}
Confusion Matrix:
[[5287   39]
 [ 112   80]]
--------------------------------------------------



Epoch 21/50 - Walking:
Train Loss: 0.0416
Val Loss: 0.1030
Val AUC: 0.9357

Detailed Metrics:
Weighted Precision: 0.9666
Weighted Recall: 0.9715
Weighted F1-score: 0.9675
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5413, 1: 105}
Confusion Matrix:
[[5291   35]
 [ 122   70]]
--------------------------------------------------



Epoch 22/50 - Walking:
Train Loss: 0.0397
Val Loss: 0.1001
Val AUC: 0.9379

Detailed Metrics:
Weighted Precision: 0.9662
Weighted Recall: 0.9670
Weighted F1-score: 0.9666
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5336, 1: 182}
Confusion Matrix:
[[5240   86]
 [  96   96]]
--------------------------------------------------



Epoch 23/50 - Walking:
Train Loss: 0.0366
Val Loss: 0.1128
Val AUC: 0.9310

Detailed Metrics:
Weighted Precision: 0.9673
Weighted Recall: 0.9717
Weighted F1-score: 0.9683
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5402, 1: 116}
Confusion Matrix:
[[5286   40]
 [ 116   76]]
--------------------------------------------------



Epoch 24/50 - Walking:
Train Loss: 0.0345
Val Loss: 0.1105
Val AUC: 0.9284

Detailed Metrics:
Weighted Precision: 0.9658
Weighted Recall: 0.9659
Weighted F1-score: 0.9658
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5328, 1: 190}
Confusion Matrix:
[[5233   93]
 [  95   97]]
--------------------------------------------------



Epoch 25/50 - Walking:
Train Loss: 0.0330
Val Loss: 0.1260
Val AUC: 0.9281

Detailed Metrics:
Weighted Precision: 0.9658
Weighted Recall: 0.9690
Weighted F1-score: 0.9671
Support: 5518.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 5326, 1: 192}
Predictions distribution: {0: 5369, 1: 149}
Confusion Matrix:
[[5262   64]
 [ 107   85]]

Early stopping triggered for Walking
Best metrics achieved:
F1 Score: 0.5145
Precision: 0.6723
Recall: 0.4167
AUC: 0.9376



Final results for StartHesitation:
Precision: 0.7868
Recall: 0.4196
F1 Score: 0.5473
AUC: 0.9313
Confusion Matrix:
[[5234   29]
 [ 148  107]]

Final results for Turn:
Precision: 0.7685
Recall: 0.7988
F1 Score: 0.7834
AUC: 0.9385
Confusion Matrix:
[[3600  372]
 [ 311 1235]]

Final results for Walking:
Precision: 0.5705
Recall: 0.4427
F1 Score: 0.4985
AUC: 0.9281
Confusion Matrix:
[[5262   64]
 [ 107   85]]


In [27]:
dataframes = []
directory_path = os.path.join(os.getcwd(), 'defog_data')
print(directory_path)

/Users/Mateo/FOGproject/notebooks/defog_data


In [28]:
for filename in os.listdir(directory_path):
    if filename.endswith('.csv'):
        # Full path to the file
        file_path = os.path.join(directory_path, filename)
        # Extract patient ID from the file name (before '.csv')
        patient_id = filename.split('.')[0]
        # Read the CSV file
        df = pd.read_csv(file_path)
        # Add patient ID column
        df['PatientID'] = patient_id
        # Append to the list of dataframes
        dataframes.append(df)

# Combine all dataframes into one
defog_df = pd.concat(dataframes, ignore_index=True)

defog_df.head(10)

Time      AccV     AccML     AccAP  StartHesitation  Turn  Walking  Valid  \
0     0 -1.035290  0.121326 -0.183682                0     0        0  False   
1     1 -1.037887  0.116788 -0.189828                0     0        0  False   
2     2 -1.014818  0.125752 -0.174294                0     0        0  False   
3     3 -1.000146  0.128355 -0.156082                0     0        0  False   
4     4 -0.985992  0.117344 -0.141497                0     0        0  False   
5     5 -0.977788  0.105946 -0.124575                0     0        0  False   
6     6 -0.979650  0.096025 -0.113552                0     0        0  False   
7     7 -0.994607  0.086037 -0.122174                0     0        0  False   
8     8 -1.016418  0.075515 -0.131091                0     0        0  False   
9     9 -1.017296  0.060953 -0.127201                0     0        0  False   

    Task   PatientID  
0  False  3f970065e5  
1  False  3f970065e5  
2  False  3f970065e5  
3  False  3f970065e5  
4  False  3f970065e5  
5  False  3f970065e5  
6  False  3f970065e5  
7  False  3f970065e5  
8  False  3f970065e5  
9  False  3f970065e5

In [29]:
results = train_fog_models(defog_df)

# Print final results for each FOG type
for fog_type, result in results.items():
    print(f"\nFinal results for {fog_type}:")
    metrics = result['metrics']
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1 Score: {metrics['f1']:.4f}")
    print(f"AUC: {metrics['auc']:.4f}")
    print("Confusion Matrix:")
    print(metrics['confusion_matrix'])


Training model for StartHesitation



Epoch 1/50 - StartHesitation:
Train Loss: 0.0081
Val Loss: 0.0034
Val AUC: 0.7847

Detailed Metrics:
Weighted Precision: 0.9994
Weighted Recall: 0.9997
Weighted F1-score: 0.9996
Support: 10567.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 10564, 1: 3}
Predictions distribution: {0: 10567, 1: 0}
Confusion Matrix:
[[10564     0]
 [    3     0]]
--------------------------------------------------



Epoch 2/50 - StartHesitation:
Train Loss: 0.0025
Val Loss: 0.0032
Val AUC: 0.7217

Detailed Metrics:
Weighted Precision: 0.9994
Weighted Recall: 0.9997
Weighted F1-score: 0.9996
Support: 10567.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 10564, 1: 3}
Predictions distribution: {0: 10567, 1: 0}
Confusion Matrix:
[[10564     0]
 [    3     0]]
--------------------------------------------------



Epoch 3/50 - StartHesitation:
Train Loss: 0.0022
Val Loss: 0.0030
Val AUC: 0.7793

Detailed Metrics:
Weighted Precision: 0.9994
Weighted Recall: 0.9997
Weighted F1-score: 0.9996
Support: 10567.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 10564, 1: 3}
Predictions distribution: {0: 10567, 1: 0}
Confusion Matrix:
[[10564     0]
 [    3     0]]
--------------------------------------------------



Epoch 4/50 - StartHesitation:
Train Loss: 0.0025
Val Loss: 0.0034
Val AUC: 0.7600

Detailed Metrics:
Weighted Precision: 0.9994
Weighted Recall: 0.9997
Weighted F1-score: 0.9996
Support: 10567.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 10564, 1: 3}
Predictions distribution: {0: 10567, 1: 0}
Confusion Matrix:
[[10564     0]
 [    3     0]]
--------------------------------------------------



Epoch 5/50 - StartHesitation:
Train Loss: 0.0027
Val Loss: 0.0026
Val AUC: 0.8537

Detailed Metrics:
Weighted Precision: 0.9994
Weighted Recall: 0.9997
Weighted F1-score: 0.9996
Support: 10567.0

Class-wise Metrics:
No predictions for Class 0 (No FOG)
No predictions for Class 1 (FOG)

Class Distribution:
Labels distribution: {0: 10564, 1: 3}
Predictions distribution: {0: 10567, 1: 0}
Confusion Matrix:
[[10564     0]
 [    3     0]]

Early stopping triggered for StartHesitation
Best metrics achieved:


TypeError: 'NoneType' object is not subscriptable